#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(RNTurbolinksManager, NSObject)
RCT_EXTERN_METHOD(reloadVisitable)
RCT_EXTERN_METHOD(reloadSession:(BOOL))
RCT_EXTERN_METHOD(dismiss)
RCT_EXTERN_METHOD(popToRoot)
RCT_EXTERN_METHOD(back)
RCT_EXTERN_METHOD(visit:(NSDictionary *) initial:(BOOL))
RCT_EXTERN_METHOD(replaceWith:(NSDictionary *) tabIndex:(NSInteger *))
RCT_EXTERN_METHOD(setUserAgent:(NSString *))
RCT_EXTERN_METHOD(setMessageHandler:(NSString *))
RCT_EXTERN_METHOD(setNavigationBarStyle:(NSDictionary *))
RCT_EXTERN_METHOD(setLoadingView:(NSString *))
RCT_EXTERN_METHOD(setNavigationBarHidden:(BOOL))
RCT_EXTERN_METHOD(renderTitle:(NSString *) subtitle:(NSString *) tabIndex:(NSInteger *))
RCT_EXTERN_METHOD(renderActions:(NSArray *) tabIndex:(NSInteger *))
RCT_EXTERN_METHOD(visitTabBar:(NSArray *) selectedIndex:(NSInteger *))
RCT_EXTERN_METHOD(setTabBarStyle:(NSDictionary *))
RCT_EXTERN_METHOD(evaluateJavaScript:(NSString *) tabIndex:(NSInteger *) resolve:(RCTPromiseResolveBlock *) reject:(RCTPromiseRejectBlock *))
@end
